---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/e_transportations/outside_power_report":
    get:
      summary: Report of e-Transportations outside power
      tags:
      - ETransportations
      responses:
        '200':
          description: report found
  "/api/v1/e_transportations":
    get:
      summary: List all e-Transportations
      tags:
      - ETransportations
      parameters:
      - name: type
        in: query
        schema:
          type: string
          enum:
          - EBike
          - EScooter
        required: false
        description: Type of transportation
      responses:
        '200':
          description: e_scooters found
    post:
      summary: Create a e-Transportation
      tags:
      - ETransportations
      parameters:
      - name: type
        in: query
        schema:
          type: string
          enum:
          - EBike
          - EScooter
        required: true
        description: Type of transportation
      responses:
        '201':
          description: e_scooter created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                owner_id:
                  type: integer
                sensor_type:
                  type: string
                  enum:
                  - small
                  - medium
                  - large
                lost_sensor:
                  type: boolean
                in_zone:
                  type: boolean
              required:
              - owner_id
              - sensor_type
  "/api/v1/e_transportations/{id}":
    get:
      summary: Show a e-Transportation
      tags:
      - ETransportations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
          enum:
          - EBike
          - EScooter
        required: false
        description: Type of transportation
      responses:
        '200':
          description: e_transportation found
        '404':
          description: e_transportation not found
    put:
      summary: Update a e-Transportation
      tags:
      - ETransportations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
          enum:
          - EBike
          - EScooter
        required: false
        description: Type of transportation
      responses:
        '200':
          description: e_scooter updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                owner_id:
                  type: integer
                sensor_type:
                  type: string
                lost_sensor:
                  type: boolean
                in_zone:
                  type: boolean
              required:
              - owner_id
              - sensor_type
    delete:
      summary: Delete a e-Transportation
      tags:
      - ETransportations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
          enum:
          - EBike
          - EScooter
        required: false
        description: Type of transportation
      responses:
        '204':
          description: e_transportation deleted
        '404':
          description: e_transportation not found
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: www.example.com
